### ISSUE TITLE
Mousepad effects not behaving

### ISSUE THREAD

**Issue by d-rez** [Vaypron/ChromaPy#2]
For some reason unless I specifically run `print()` (with or without an argument) right in front of Chroma.Mousemat effect set and apply calls, there's no reaction on the Razer mug (which is being detected as a chroma mouse pad).

This makes my python script output useless lines of emptiness. Tested with Python3.5 lib compiled from current source 454ae1d899758be23a7442aa91afe1613ddfdbe5

Were you able to test effects on a mouse pad? I tried running commands manually in python CLI but I'm getting very inconsistent results. This applies to setColor, setbyGrid and other effects (most never start even after running `applyLED()`)

I'm gonna try to troubleshoot it a bit more by myself as well but maybe you have an idea as to why

**Comment by tngebauer** [comment]
That's interesting. I encountered similar problems before with my chroma mouse. I don't really know how they were solved(maybe a synapse update or a restart), but I just compiled the current version of ChromaPy and all my Firefly(Mousemat), Ornata(Keyboard) and Mamba(Mouse) are behaving as they should. 
`Mousepad.setColor((255,0,0))`
`Mousepad.applyLED()`
are working as well as 
`Mousepad.setWave(1)`

Got a feeling that the inconsistency is due to the Chroma SDK itself.

**Comment by d-rez** [comment]
Interesting. I might try using different SDK versions to verify as I have an [archive of that](https://www.reddit.com/r/razer/wiki/synapse-updates#wiki_razer_chroma_sdk_core)

Mouse works fine, it's just the mousepad in this case. Thanks for your input, I'll look into it on my end a bit more. Still, why the heck would it need a print() out of all calls lol

**Comment by tngebauer** [comment]
If I remember right, I had a python script running and nothing happened. So I added a print to real-time-debug the values and et voilà it worked. So same behavior.
Definitely keep me posted! :)
